# Generated by Django 2.1.5 on 2019-02-23 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20190221_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moeny', models.IntegerField(default=0)),
                ('item_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Item')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Person')),
            ],
        ),
    ]
