# Generated by Django 2.1.5 on 2019-02-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_item_in_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_list',
        ),
        migrations.AlterField(
            model_name='item',
            name='in_cart',
            field=models.IntegerField(default=0),
        ),
    ]
