# Generated by Django 2.1.5 on 2019-02-23 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_auto_20190223_0219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='moeny',
            new_name='money',
        ),
    ]
