# Generated by Django 2.1.5 on 2019-02-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_auto_20190223_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='number',
        ),
        migrations.AlterField(
            model_name='history',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
